### ISSUE TITLE
ValidationError: child "redirectTo" fails because ["redirectTo" must be a string]

### ISSUE THREAD

**Issue by gauravgupta90** [Kevin-A/AuthProject#2]
I cloned the project and tried to run, but got the error.

I also tried with previous version commit 5e0e277
@Kevin-A Kevin-A authored on 4 Mar, it worked perfectly. I guess the issue is due to updating version of hapi and hapi-auth-cookie.

![capture](https://cloud.githubusercontent.com/assets/5506548/7366317/138f0d62-edb5-11e4-88cc-65528658f059.PNG)

**Comment by Kevin-A** [comment]
You were correct. In the newer versions of `hapi-auth-cookie` it is no longer necessary.
